services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: sentimentiq
      POSTGRES_USER: sentiq
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis
  
  inference:
    build: ./inference
    ports:
      - "8001:8001"
    volumes:
      - ./inference:/app
      - hf_cache:/root/.cache/huggingface 
    env_file: .env

volumes:
  pg_data:
  hf_cache:        

  