# Generated by Django 6.0.5 on 2026-05-24 12:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('hotel_name', models.CharField(max_length=255)),
                ('reviewer', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], db_index=True, max_length=20)),
                ('model_used', models.CharField(choices=[('roberta', 'RoBERTa'), ('vader', 'VADER')], max_length=20)),
                ('confidence', models.FloatField()),
                ('pos_score', models.FloatField(default=0)),
                ('neu_score', models.FloatField(default=0)),
                ('neg_score', models.FloatField(default=0)),
                ('shap_scores', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='reviews.review')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='reviews.source'),
        ),
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('room', 'Room'), ('staff', 'Staff'), ('food', 'Food'), ('value', 'Value'), ('cleanliness', 'Cleanliness'), ('location', 'Location'), ('other', 'Other')], db_index=True, max_length=20)),
                ('label', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
                ('confidence', models.FloatField()),
                ('keywords', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='reviews.review')),
            ],
            options={
                'unique_together': {('review', 'category')},
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['hotel_name', 'status'], name='reviews_rev_hotel_n_290f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewed_at'], name='reviews_rev_reviewe_5e3530_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('source', 'external_id')},
        ),
    ]
