# Generated by Django 6.0.5 on 2026-06-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', False), models.Q(('external_id', ''), _negated=True)), fields=('source', 'external_id'), name='unique_review_per_source'),
        ),
    ]
