# Generated by Django 6.0.5 on 2026-06-08 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('target_url', models.URLField()),
                ('hotel_name', models.CharField(blank=True, max_length=255)),
                ('event', models.CharField(choices=[('review.done', 'Review Done'), ('sentiment.drop', 'Sentiment Drop')], default='review.done', max_length=30)),
                ('secret', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response', models.TextField(blank=True)),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='reviews.review')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reviews.webhooksubscription')),
            ],
        ),
    ]
