# Generated by Django 6.0.5 on 2026-06-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_webhooksubscription_webhooklog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhooksubscription',
            options={'ordering': ['-created_at']},
        ),
    ]
